package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpString;
import com.sun.management.snmp.SnmpStatusException;
import static tigase.management.StatisticsConstatnts.*;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "TigaseUser" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.16120609.2.145.3.163.1.1.1.
 */
public class TigaseUser implements TigaseUserMBean, Serializable {

    /**
     * Variable for storing the value of "TigaseUserRegisteredCount".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.1.2".
     */
    protected Long TigaseUserRegisteredCount = new Long(1);

    /**
     * Variable for storing the value of "TigaseUserSessionCount".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.1.1".
     */
    protected Long TigaseUserSessionCount = new Long(1);


    /**
     * Constructor for the "TigaseUser" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public TigaseUser(SnmpMib myMib) {
    }


    /**
     * Constructor for the "TigaseUser" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public TigaseUser(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "TigaseUserRegisteredCount" variable.
     */
    public Long getTigaseUserRegisteredCount() throws SnmpStatusException {
      TigaseUserRegisteredCount = 
							StatisticsUtils.getStatsValue(SM_COMP, REGISTERED_USERS_STAT,
							TigaseUserRegisteredCount);
			return TigaseUserRegisteredCount;
    }

    /**
     * Getter for the "TigaseUserSessionCount" variable.
     */
    public Long getTigaseUserSessionCount() throws SnmpStatusException {
      TigaseUserSessionCount = StatisticsUtils.getStatsValue(SM_COMP, OPEN_SESSIONS_STAT,
							TigaseUserSessionCount);
			return TigaseUserSessionCount;
    }

}
