package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "TigaseConnection" MBean.
 */
public interface TigaseConnectionMBean {

    /**
     * Getter for the "TigaseConnectionBoshCount" variable.
     */
    public Long getTigaseConnectionBoshCount() throws SnmpStatusException;

    /**
     * Getter for the "TigaseConnectionServerCount" variable.
     */
    public Long getTigaseConnectionServerCount() throws SnmpStatusException;

    /**
     * Getter for the "TigaseConnectionClientCount" variable.
     */
    public Long getTigaseConnectionClientCount() throws SnmpStatusException;

}
