package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "TigaseLoad" MBean.
 */
public interface TigaseLoadMBean {

    /**
     * Getter for the "TigaseLoadBoshLastSecond" variable.
     */
    public Long getTigaseLoadBoshLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadC2SLastHour" variable.
     */
    public Long getTigaseLoadC2SLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadC2SLastMinute" variable.
     */
    public Long getTigaseLoadC2SLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadC2SLastSecond" variable.
     */
    public Long getTigaseLoadC2SLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadS2SLastHour" variable.
     */
    public Long getTigaseLoadS2SLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadS2SLastMinute" variable.
     */
    public Long getTigaseLoadS2SLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadS2SLastSecond" variable.
     */
    public Long getTigaseLoadS2SLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadPubSubLastHour" variable.
     */
    public Long getTigaseLoadPubSubLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadPubSubLastMinute" variable.
     */
    public Long getTigaseLoadPubSubLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadPubSubLastSecond" variable.
     */
    public Long getTigaseLoadPubSubLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMUCLastHour" variable.
     */
    public Long getTigaseLoadMUCLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMUCLastMinute" variable.
     */
    public Long getTigaseLoadMUCLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMUCLastSecond" variable.
     */
    public Long getTigaseLoadMUCLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMRLastHour" variable.
     */
    public Long getTigaseLoadMRLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMRLastMinute" variable.
     */
    public Long getTigaseLoadMRLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadMRLastSecond" variable.
     */
    public Long getTigaseLoadMRLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadSMLastHour" variable.
     */
    public Long getTigaseLoadSMLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadSMLastMinute" variable.
     */
    public Long getTigaseLoadSMLastMinute() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadSMLastSecond" variable.
     */
    public Long getTigaseLoadSMLastSecond() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadBoshLastHour" variable.
     */
    public Long getTigaseLoadBoshLastHour() throws SnmpStatusException;

    /**
     * Getter for the "TigaseLoadBoshLastMinute" variable.
     */
    public Long getTigaseLoadBoshLastMinute() throws SnmpStatusException;

}
