/*
 * TigaseLoad.java
 *
 * Tigase Jabber/XMPP Server - Extras
 * Copyright (C) 2004-2017 "Tigase, Inc." <office@tigase.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. Look for COPYING file in the top folder.
 * If not, see http://www.gnu.org/licenses/.
 */

package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpStatusException;
import static tigase.management.StatisticsConstatnts.*;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "TigaseLoad" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.
 */
public class TigaseLoad implements TigaseLoadMBean, Serializable {

    /**
     * Variable for storing the value of "TigaseLoadBoshLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.19".
     */
    protected Long TigaseLoadBoshLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadC2SLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.18".
     */
    protected Long TigaseLoadC2SLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadC2SLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.17".
     */
    protected Long TigaseLoadC2SLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadC2SLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.16".
     */
    protected Long TigaseLoadC2SLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadS2SLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.15".
     */
    protected Long TigaseLoadS2SLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadS2SLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.14".
     */
    protected Long TigaseLoadS2SLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadS2SLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.13".
     */
    protected Long TigaseLoadS2SLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadPubSubLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.12".
     */
    protected Long TigaseLoadPubSubLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadPubSubLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.11".
     */
    protected Long TigaseLoadPubSubLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadPubSubLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.10".
     */
    protected Long TigaseLoadPubSubLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMUCLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.9".
     */
    protected Long TigaseLoadMUCLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMUCLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.8".
     */
    protected Long TigaseLoadMUCLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMUCLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.7".
     */
    protected Long TigaseLoadMUCLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMRLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.6".
     */
    protected Long TigaseLoadMRLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMRLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.5".
     */
    protected Long TigaseLoadMRLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadMRLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.4".
     */
    protected Long TigaseLoadMRLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadSMLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.3".
     */
    protected Long TigaseLoadSMLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadSMLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.2".
     */
    protected Long TigaseLoadSMLastMinute = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadSMLastSecond".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.1".
     */
    protected Long TigaseLoadSMLastSecond = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadBoshLastHour".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.21".
     */
    protected Long TigaseLoadBoshLastHour = new Long(1);

    /**
     * Variable for storing the value of "TigaseLoadBoshLastMinute".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.3.20".
     */
    protected Long TigaseLoadBoshLastMinute = new Long(1);


    /**
     * Constructor for the "TigaseLoad" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public TigaseLoad(SnmpMib myMib) {
    }


    /**
     * Constructor for the "TigaseLoad" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public TigaseLoad(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "TigaseLoadBoshLastSecond" variable.
     */
    public Long getTigaseLoadBoshLastSecond() throws SnmpStatusException {
      TigaseLoadBoshLastSecond = 
							StatisticsUtils.getStatsValue(BOSH_COMP, LAST_SECOND_STAT,
							TigaseLoadBoshLastSecond);
			return TigaseLoadBoshLastSecond;
    }

    /**
     * Getter for the "TigaseLoadC2SLastHour" variable.
     */
    public Long getTigaseLoadC2SLastHour() throws SnmpStatusException {
      TigaseLoadC2SLastHour = 
							StatisticsUtils.getStatsValue(CLI_COMP, LAST_HOUR_STAT,
							TigaseLoadC2SLastHour);
			return TigaseLoadC2SLastHour;
    }

    /**
     * Getter for the "TigaseLoadC2SLastMinute" variable.
     */
    public Long getTigaseLoadC2SLastMinute() throws SnmpStatusException {
      TigaseLoadC2SLastMinute =
							StatisticsUtils.getStatsValue(CLI_COMP, LAST_MINUTE_STAT,
							TigaseLoadC2SLastMinute);
        return TigaseLoadC2SLastMinute;
    }

    /**
     * Getter for the "TigaseLoadC2SLastSecond" variable.
     */
    public Long getTigaseLoadC2SLastSecond() throws SnmpStatusException {
      TigaseLoadC2SLastSecond =
							StatisticsUtils.getStatsValue(CLI_COMP, LAST_SECOND_STAT,
							TigaseLoadC2SLastSecond);
        return TigaseLoadC2SLastSecond;
    }

    /**
     * Getter for the "TigaseLoadS2SLastHour" variable.
     */
    public Long getTigaseLoadS2SLastHour() throws SnmpStatusException {
      TigaseLoadS2SLastHour = 
							StatisticsUtils.getStatsValue(SRV_COMP, LAST_HOUR_STAT,
							TigaseLoadS2SLastHour);
			return TigaseLoadS2SLastHour;
    }

    /**
     * Getter for the "TigaseLoadS2SLastMinute" variable.
     */
    public Long getTigaseLoadS2SLastMinute() throws SnmpStatusException {
      TigaseLoadS2SLastMinute =
							StatisticsUtils.getStatsValue(SRV_COMP, LAST_MINUTE_STAT,
							TigaseLoadS2SLastMinute);
			return TigaseLoadS2SLastMinute;
    }

    /**
     * Getter for the "TigaseLoadS2SLastSecond" variable.
     */
    public Long getTigaseLoadS2SLastSecond() throws SnmpStatusException {
      TigaseLoadS2SLastSecond =
							StatisticsUtils.getStatsValue(SRV_COMP, LAST_SECOND_STAT,
							TigaseLoadS2SLastSecond);
			return TigaseLoadS2SLastSecond;
    }

    /**
     * Getter for the "TigaseLoadPubSubLastHour" variable.
     */
    public Long getTigaseLoadPubSubLastHour() throws SnmpStatusException {
      TigaseLoadPubSubLastHour =
							StatisticsUtils.getStatsValue(PUBSUB_COMP, LAST_HOUR_STAT,
							TigaseLoadPubSubLastHour);
			return TigaseLoadPubSubLastHour;
    }

    /**
     * Getter for the "TigaseLoadPubSubLastMinute" variable.
     */
    public Long getTigaseLoadPubSubLastMinute() throws SnmpStatusException {
			TigaseLoadPubSubLastMinute =
							StatisticsUtils.getStatsValue(PUBSUB_COMP, LAST_MINUTE_STAT,
							TigaseLoadPubSubLastMinute);
			return TigaseLoadPubSubLastMinute;
    }

    /**
     * Getter for the "TigaseLoadPubSubLastSecond" variable.
     */
    public Long getTigaseLoadPubSubLastSecond() throws SnmpStatusException {
      TigaseLoadPubSubLastSecond =
							StatisticsUtils.getStatsValue(PUBSUB_COMP, LAST_SECOND_STAT,
							TigaseLoadPubSubLastSecond);
			return TigaseLoadPubSubLastSecond;
    }

    /**
     * Getter for the "TigaseLoadMUCLastHour" variable.
     */
    public Long getTigaseLoadMUCLastHour() throws SnmpStatusException {
      TigaseLoadMUCLastHour =
							StatisticsUtils.getStatsValue(MUC_COMP, LAST_HOUR_STAT,
							TigaseLoadMUCLastHour);
			return TigaseLoadMUCLastHour;
    }

    /**
     * Getter for the "TigaseLoadMUCLastMinute" variable.
     */
    public Long getTigaseLoadMUCLastMinute() throws SnmpStatusException {
      TigaseLoadMUCLastMinute =
							StatisticsUtils.getStatsValue(MUC_COMP, LAST_MINUTE_STAT,
							TigaseLoadMUCLastMinute);
			return TigaseLoadMUCLastMinute;
    }

    /**
     * Getter for the "TigaseLoadMUCLastSecond" variable.
     */
    public Long getTigaseLoadMUCLastSecond() throws SnmpStatusException {
      TigaseLoadMUCLastSecond =
							StatisticsUtils.getStatsValue(MUC_COMP, LAST_SECOND_STAT,
							TigaseLoadMUCLastSecond);
			return TigaseLoadMUCLastSecond;
    }

    /**
     * Getter for the "TigaseLoadMRLastHour" variable.
     */
    public Long getTigaseLoadMRLastHour() throws SnmpStatusException {
      TigaseLoadMRLastHour =
							StatisticsUtils.getStatsValue(MR_COMP, LAST_HOUR_STAT,
							TigaseLoadMRLastHour);
			return TigaseLoadMRLastHour;
    }

    /**
     * Getter for the "TigaseLoadMRLastMinute" variable.
     */
    public Long getTigaseLoadMRLastMinute() throws SnmpStatusException {
      TigaseLoadMRLastMinute =
							StatisticsUtils.getStatsValue(MR_COMP, LAST_MINUTE_STAT,
							TigaseLoadMRLastMinute);
			return TigaseLoadMRLastMinute;
    }

    /**
     * Getter for the "TigaseLoadMRLastSecond" variable.
     */
    public Long getTigaseLoadMRLastSecond() throws SnmpStatusException {
      TigaseLoadMRLastSecond =
							StatisticsUtils.getStatsValue(MR_COMP, LAST_SECOND_STAT,
							TigaseLoadMRLastSecond);
			return TigaseLoadMRLastSecond;
    }

    /**
     * Getter for the "TigaseLoadSMLastHour" variable.
     */
    public Long getTigaseLoadSMLastHour() throws SnmpStatusException {
      TigaseLoadSMLastHour =
							StatisticsUtils.getStatsValue(SM_COMP, LAST_HOUR_STAT,
							TigaseLoadSMLastHour);
			return TigaseLoadSMLastHour;
    }

    /**
     * Getter for the "TigaseLoadSMLastMinute" variable.
     */
    public Long getTigaseLoadSMLastMinute() throws SnmpStatusException {
      TigaseLoadSMLastMinute =
							StatisticsUtils.getStatsValue(SM_COMP, LAST_MINUTE_STAT,
							TigaseLoadSMLastMinute);
			return TigaseLoadSMLastMinute;
    }

    /**
     * Getter for the "TigaseLoadSMLastSecond" variable.
     */
    public Long getTigaseLoadSMLastSecond() throws SnmpStatusException {
      TigaseLoadSMLastSecond =
							StatisticsUtils.getStatsValue(SM_COMP, LAST_SECOND_STAT,
							TigaseLoadSMLastSecond);
			return TigaseLoadSMLastSecond;
    }

    /**
     * Getter for the "TigaseLoadBoshLastHour" variable.
     */
    public Long getTigaseLoadBoshLastHour() throws SnmpStatusException {
      TigaseLoadBoshLastHour =
							StatisticsUtils.getStatsValue(BOSH_COMP, LAST_HOUR_STAT,
							TigaseLoadBoshLastHour);
			return TigaseLoadBoshLastHour;
    }

    /**
     * Getter for the "TigaseLoadBoshLastMinute" variable.
     */
    public Long getTigaseLoadBoshLastMinute() throws SnmpStatusException {
      TigaseLoadBoshLastMinute =
							StatisticsUtils.getStatsValue(BOSH_COMP, LAST_MINUTE_STAT,
							TigaseLoadBoshLastMinute);
			return TigaseLoadBoshLastMinute;
    }

}
