version: 40
imports:
- projectPath: Templates
  revision: main
jobs:
- name: Maven CI
  steps:
  - !UseTemplateStep
    name: maven build & deploy
    templateName: Tigase Server - Maven build & deploy
    paramMatrix:
    - name: timestamp-to-make-distinct
      valuesProvider: !ScriptingValues
        scriptName: get-timestamp
      secret: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
