package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB.
//

// java imports
//
import java.io.Serializable;

// jmx imports
//
import javax.management.MBeanServer;
import com.sun.management.snmp.SnmpStatusException;
import static tigase.management.StatisticsConstatnts.*;

// jdmk imports
//
import com.sun.management.snmp.agent.SnmpMib;

/**
 * The class is used for implementing the "TigaseConnection" group.
 * The group is defined with the following oid: 1.3.6.1.4.1.16120609.2.145.3.163.1.1.2.
 */
public class TigaseConnection implements TigaseConnectionMBean, Serializable {

    /**
     * Variable for storing the value of "TigaseConnectionBoshCount".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.2.3".
     */
    protected Long TigaseConnectionBoshCount = new Long(1);

    /**
     * Variable for storing the value of "TigaseConnectionServerCount".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.2.2".
     */
    protected Long TigaseConnectionServerCount = new Long(1);

    /**
     * Variable for storing the value of "TigaseConnectionClientCount".
     * The variable is identified by: "1.3.6.1.4.1.16120609.2.145.3.163.1.1.2.1".
     */
    protected Long TigaseConnectionClientCount = new Long(1);


    /**
     * Constructor for the "TigaseConnection" group.
     * If the group contains a table, the entries created through an SNMP SET will not be registered in Java DMK.
     */
    public TigaseConnection(SnmpMib myMib) {
    }


    /**
     * Constructor for the "TigaseConnection" group.
     * If the group contains a table, the entries created through an SNMP SET will be AUTOMATICALLY REGISTERED in Java DMK.
     */
    public TigaseConnection(SnmpMib myMib, MBeanServer server) {
    }

    /**
     * Getter for the "TigaseConnectionBoshCount" variable.
     */
    public Long getTigaseConnectionBoshCount() throws SnmpStatusException {
      TigaseConnectionBoshCount = 
							StatisticsUtils.getStatsValue(BOSH_COMP, OPEN_CONN_STAT,
							TigaseConnectionBoshCount);
			return TigaseConnectionBoshCount;
    }

    /**
     * Getter for the "TigaseConnectionServerCount" variable.
     */
    public Long getTigaseConnectionServerCount() throws SnmpStatusException {
      TigaseConnectionServerCount =
							StatisticsUtils.getStatsValue(SRV_COMP, OPEN_CONN_STAT,
							TigaseConnectionServerCount);
			return TigaseConnectionServerCount;
    }

    /**
     * Getter for the "TigaseConnectionClientCount" variable.
     */
    public Long getTigaseConnectionClientCount() throws SnmpStatusException {
      TigaseConnectionClientCount = StatisticsUtils.getStatsValue(CLI_COMP,
							OPEN_CONN_STAT, TigaseConnectionClientCount);
			return TigaseConnectionClientCount;
    }

}
