package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "TigaseUser" MBean.
 */
public interface TigaseUserMBean {

    /**
     * Getter for the "TigaseUserRegisteredCount" variable.
     */
    public Long getTigaseUserRegisteredCount() throws SnmpStatusException;

    /**
     * Getter for the "TigaseUserSessionCount" variable.
     */
    public Long getTigaseUserSessionCount() throws SnmpStatusException;

}
