package tigase.management;

//
// Generated by mibgen version 5.1 (03/08/07) when compiling TIGASE-MANAGEMENT-MIB in standard metadata mode.
//


// jmx imports
//
import com.sun.management.snmp.SnmpStatusException;

/**
 * This interface is used for representing the remote management interface for the "TigaseSystem" MBean.
 */
public interface TigaseSystemMBean {

    /**
     * Getter for the "TigaseSystemUptimeHumanReadable" variable.
     */
    public String getTigaseSystemUptimeHumanReadable() throws SnmpStatusException;

    /**
     * Getter for the "TigaseSystemUptimeMillis" variable.
     */
    public Long getTigaseSystemUptimeMillis() throws SnmpStatusException;

    /**
     * Getter for the "TigaseSystemNonHeapUsed" variable.
     */
    public Long getTigaseSystemNonHeapUsed() throws SnmpStatusException;

    /**
     * Getter for the "TigaseSystemNonHeapTotal" variable.
     */
    public Long getTigaseSystemNonHeapTotal() throws SnmpStatusException;

    /**
     * Getter for the "TigaseSystemHeapUsed" variable.
     */
    public Long getTigaseSystemHeapUsed() throws SnmpStatusException;

    /**
     * Getter for the "TigaseSystemHeapTotal" variable.
     */
    public Long getTigaseSystemHeapTotal() throws SnmpStatusException;

}
